#!/usr/bin/env python3
"""Devocionais rotativos por dia do mês. Índice = (dia - 1) % total."""

DEVOCIONAIS = [
    ("Salmos 46:10", "Aquietai-vos e sabei que eu sou Deus.",
     "Em meio ao caos do dia, Deus convida você a parar. A paz não vem de resolver tudo, mas de confiar nAquele que já resolveu."),
    ("Filipenses 4:13", "Tudo posso naquele que me fortalece.",
     "Não é sobre a sua capacidade, é sobre a fonte de onde você bebe. Quando a força humana acaba, a de Deus começa."),
    ("Jeremias 29:11", "Eu sei os planos que tenho para você, planos de paz e não de mal, para dar a você um futuro e uma esperança.",
     "Deus não desistiu de você. Mesmo nos dias sem saída, há um plano maior sendo tecido."),
    ("Isaías 40:31", "Os que esperam no Senhor renovam as suas forças; voam alto como águias.",
     "Esperar em Deus não é passividade — é fé em ação. Enquanto você descansa nEle, Ele trabalha por você."),
    ("João 3:16", "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito.",
     "O maior amor da história não foi um sentimento — foi uma decisão. Hoje você é lembrado: você é amado assim."),
    ("Romanos 8:28", "Todas as coisas cooperam para o bem daqueles que amam a Deus.",
     "Nem tudo que acontece é bom, mas Deus usa tudo para o bem. Confie no processo, mesmo quando dói."),
    ("Provérbios 3:5", "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento.",
     "Nossa mente tem limites. A sabedoria de Deus não. Entregar o controle é o ato mais corajoso que existe."),
    ("Mateus 11:28", "Venham a mim todos os que estão cansados e sobrecarregados, e eu darei descanso a vocês.",
     "Jesus não pede que você chegue arrumado. Ele convida você como está — cansado e cheio de dúvidas."),
    ("2 Coríntios 5:7", "Pois caminhamos por fé e não pelo que vemos.",
     "Fé é dar o passo mesmo sem ver o chão. Deus não pede que você enxergue o final — só o próximo passo."),
    ("Salmos 23:1", "O Senhor é o meu pastor e nada me faltará.",
     "Quando o Pastor cuida, a ovelha não carece. Hoje, permita-se ser cuidado por Deus."),
    ("Gálatas 6:9", "Não nos cansemos de fazer o bem, pois no tempo certo colheremos, se não desanimarmos.",
     "A colheita tem tempo certo. Continue semeando bondade, mesmo quando o solo parece seco."),
    ("Salmos 121:2", "O meu socorro vem do Senhor, que fez o céu e a terra.",
     "O mesmo Deus que criou o universo está de olho em você hoje. Nenhum detalhe da sua vida passa despercebido."),
    ("Efésios 3:20", "Àquele que é poderoso para fazer infinitamente mais do que tudo o que pedimos ou pensamos.",
     "Seus maiores sonhos são pequenos perto do que Deus pode fazer. Eleve suas expectativas."),
    ("Josué 1:9", "Seja forte e corajoso! Não se apavore, pois o Senhor estará com você por onde você andar.",
     "Coragem não é ausência de medo. É decidir agir com Deus ao lado, apesar do medo."),
    ("Salmos 37:4", "Deleite-se no Senhor, e ele atenderá aos desejos do seu coração.",
     "Quando você faz de Deus a sua maior alegria, os desejos do coração se alinham com os dEle."),
    ("Isaías 41:10", "Não tenha medo, pois estou com você; não se apavore, pois sou o seu Deus.",
     "Deus não disse que não haverá tempestades. Disse que estará com você dentro delas. Isso muda tudo."),
    ("João 14:27", "A paz eu lhes deixo; a minha paz eu lhes dou. Não se perturbe o coração de vocês.",
     "A paz de Jesus não depende das circunstâncias. Ela é uma presença — não a ausência de problemas."),
    ("1 Pedro 5:7", "Lançai sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.",
     "Você não foi feito para carregar o peso do amanhã. Cada preocupação entregue a Deus é uma declaração de fé."),
    ("Romanos 8:37", "Em todas essas coisas somos mais que vencedores por meio daquele que nos amou.",
     "Não apenas vencedor — mais que vencedor. Deus não dá vitória parcial. Dá a vitória completa em Cristo."),
    ("Salmos 27:1", "O Senhor é a minha luz e a minha salvação; a quem temerei?",
     "O medo murcha na presença de Deus. Hoje, antes de olhar o problema, olhe para o Deus que é maior."),
    ("Mateus 6:33", "Buscai em primeiro lugar o Reino de Deus, e todas essas coisas lhes serão acrescentadas.",
     "Quando a prioridade está certa, o resto se organiza. Comece o dia com Deus — o resto Ele cuida."),
    ("Habacuque 3:19", "O Senhor Soberano é a minha força; ele faz os meus pés como os do cervo.",
     "Lugares altos pedem preparo. Deus está te treinando, não te abandonando. Cada dificuldade é um degrau."),
    ("Filipenses 4:6", "Não andem ansiosos por coisa alguma; em tudo, pela oração, apresentem seus pedidos a Deus.",
     "A oração transforma a ansiedade em gratidão. Fale com Deus sobre o que te preocupa — Ele ouve."),
    ("2 Timóteo 1:7", "Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio.",
     "O medo não vem de Deus. Poder, amor e mente sã — é isso que Ele colocou em você. Ande nessa verdade."),
    ("Lamentações 3:23", "As misericórdias do Senhor se renovam a cada manhã; grande é a sua fidelidade.",
     "Cada amanhecer é uma nova página. Deus não carrega seus erros de ontem — nem você precisa."),
    ("Salmos 16:8", "Tenho posto o Senhor continuamente diante de mim; não serei abalado.",
     "Estabilidade vem de foco. Quando os olhos estão em Deus, o chão pode tremer sem que você caia."),
    ("Efésios 2:10", "Somos criação de Deus, criados em Cristo Jesus para fazer boas obras.",
     "Você não é um acidente. Existe um propósito escrito antes de você nascer. Viva à altura disso."),
    ("João 10:10", "Eu vim para que tenham vida, e a tenham plenamente.",
     "Vida plena — não pela metade. Jesus não veio te dar sobrevivência, mas abundância."),
    ("Miquéias 6:8", "Praticar a justiça, amar a misericórdia e andar humildemente com o seu Deus.",
     "O resumo de uma vida boa: fazer o certo, ser compassivo e não depender de si mesmo. Simples, mas transformador."),
    ("Apocalipse 3:20", "Eis que estou à porta e bato. Se alguém ouvir a minha voz e abrir a porta, entrarei.",
     "Jesus não invade. Ele espera. A porta tem maçaneta por dentro — você decide abrir."),
]


def devocional_do_dia(dia_do_mes):
    return DEVOCIONAIS[(dia_do_mes - 1) % len(DEVOCIONAIS)]
